### PR TITLE
refactor: Remove deprecated sdk.WrapSDKContext

### PR DESCRIPTION
**Pull request by poorphd**
## Description
The sdk.WrapSDKContext function is deprecated and has been removed from the codebase. This change refactors the affected code to use the recommended alternatives, ensuring compatibility with future SDK versions and maintaining code quality.

Closes: [[L-1]](https://github.com/code-423n4/2024-05-canto-findings/issues/33)

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] targeted the correct branch (see [PR Targeting](https://github.com/canto-network/canto/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] provided a link to the relevant issue or specification
- [ ] included the necessary unit and integration tests
- [x] reviewed "Files changed" and left comments if necessary
 
### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by dudong2 — APPROVED** [review]
LGTM!

**Comment by dongsam** [comment]
Once one collaborator approves, please switch the status from draft to R4R and add subsequent reviewers. This will help ensure that we achieve the goal of receiving at least two approvals without delays.

**Review by dongsam — APPROVED** [review]
LGTM

**Comment by dongsam** [comment]
Since this PR has received two or more approvals, it would be good to merge it if there are no other issues.

**Pull request merged**
