### PR TITLE
refactor: Remove redundant EventTypeMessage emission in custom modules

### PR DESCRIPTION
**Pull request by poorphd**
## Description
EventTypeMessage events with sdk.AttributeKeyModule and sdk.AttributeKeySender are now emitted directly at message execution (in baseapp). This change removes the redundant boilerplate event emission from all custom modules.

The module name is assumed by baseapp to be the second element of the message route, e.g., "cosmos.bank.v1beta1.MsgSend" -> "bank". For modules that do not follow the standard message path (e.g., IBC), it is advised to continue emitting the module name event. Baseapp only emits the EventTypeMessage event if the module has not already done so.

This refactor ensures cleaner code and leverages the automatic event emission provided by baseapp.

Closes: [L-4](https://github.com/code-423n4/2024-05-canto-findings/issues/33)

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] targeted the correct branch (see [PR Targeting](https://github.com/canto-network/canto/blob/main/CONTRIBUTING.md#pr-targeting))
- [x] provided a link to the relevant issue or specification
- [x] included the necessary unit and integration tests
- [x] reviewed "Files changed" and left comments if necessary
 
### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed state machine logic
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by dudong2** [comment]
There are several event emit in x/\<module name\>/msg_server.go. We need to remove all event emit with sdk.AttributeKeyModule and sdk.AttributeKeySender(eg. RemoveLiquidity, ...)

**Comment by poorphd** [comment]
removed

**Review by dudong2 — APPROVED** [review]

**Review by dongsam — APPROVED** [review]
LGTM, adding the test code improved the review efficiency. Thanks 👍

**Review by zsystm — APPROVED** [review]
LGTM

**Pull request merged**
